{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sagemaker-inference-llamacpp-graviton.serviceAccountName" . }}
  labels:
    {{- include "sagemaker-inference-llamacpp-graviton.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
