# Local testing values for development
replicaCount: 1

image:
  repository: sagemaker-inference-llamacpp-graviton
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 2Gi

# Model configuration for testing
model:
  # Using a non-gated model for testing
  hfModelId: "arcee-ai/arcee-lite"
  quantization: "Q4_K_M"
  hfToken: ""  # Set your HF token if needed for gated models

# Persistence configuration
persistence:
  enabled: true
  storageClass: ""  # Use default storage class
  accessMode: ReadWriteOnce
  size: 5Gi
  hfCachePath: "/root/.cache/huggingface"
  modelsPath: "/opt/models"

# Health check configuration
healthCheck:
  enabled: true
  initialDelaySeconds: 300
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3
  successThreshold: 1

# Node selector for ARM64 (Graviton) instances - commented out for local testing
# nodeSelector:
#   kubernetes.io/arch: arm64
